swagger: "2.0"
info:
  title: Mainflux Provision service
  description: HTTP API for Provision service
  version: "1.0.0"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /mapping:
    post:
      consumes:
        - application/json
      summary: Adds new device to proxy
      description: Adds new device to proxy
      tags:
        - Thing to proxy
      parameters:
      - $ref: "#/parameters/Authorization"
      - in: body
         name: thing
         description: MAC address of device or other identifier
         schema:
           type: object
           required:
             - external_id
             - external_key
           properties:
             external_id:
               type: string
              external_key:
                type: string
              name:
                type: string
      responses:
        201:
          description: Created
        400:
          description: Failed due to malformed JSON.
        500:
          description: Unexpected server-side error ocurred.
parameters:
  Authorization:
    name: Authorization
    description: User's access token. Used instead of credentials in env or config.toml.
    in: header
    type: string
    required: false