# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

version: "3.7"

volumes:
  mainflux-mqtt-broker-volume:

services:
  nginx:
    depends_on:
      - mqtt-adapter

  vernemq:
    image: mainflux/vernemq:1.10.1-alpine
    container_name: mainflux-vernemq
    restart: on-failure
    environment:
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: "on"
      DOCKER_VERNEMQ_LOG__CONSOLE__LEVEL: info
    ports:
      - 18831:${MF_MQTT_BROKER_PORT}
      - 8881:${MF_MQTT_BROKER_WS_PORT}
      - 7777:8888
    networks:
      - mainflux-base-net
    volumes: 
      - mainflux-mqtt-broker-volume:/var/lib/vernemq
  
  mqtt-adapter:
    image: mainflux/mproxy:latest
    container_name: mainflux-mqtt
    depends_on:
      - vernemq
      - things
      - nats
    restart: on-failure
    environment:
      MF_MQTT_ADAPTER_LOG_LEVEL: ${MF_MQTT_ADAPTER_LOG_LEVEL}
      MF_MQTT_ADAPTER_PORT: ${MF_MQTT_ADAPTER_PORT}
      MF_MQTT_ADAPTER_WS_PORT: ${MF_MQTT_ADAPTER_WS_PORT}
      MF_MQTT_ADAPTER_ES_URL: es-redis:${MF_REDIS_TCP_PORT}
      MF_NATS_URL: ${MF_NATS_URL}
      MF_THINGS_URL: things:${MF_THINGS_AUTH_GRPC_PORT}
      MF_JAEGER_URL: ${MF_JAEGER_URL}
      MF_MQTT_ADAPTER_MQTT_TARGET_HOST: vernemq
      MF_MQTT_ADAPTER_MQTT_TARGET_PORT: ${MF_MQTT_BROKER_PORT}
    ports:
      - 18832:${MF_MQTT_ADAPTER_PORT}
      - 8882:${MF_MQTT_ADAPTER_WS_PORT}
    networks:
      - mainflux-base-net
